SELECT CodigoDoCliente, NomeDaEmpresa, Endereco FROM Clientes;
SELECT SobreNome, Nome, DataDeNascimento, DataDeContratacao FROM Funcionarios;
SELECT CodigoDaCategoria, NomeDaCategoria, Descricao FROM Categorias;
SELECT NomeDaEmpresa, NomeDoContato, Telefone FROM Fornecedores;
SELECT CodigoDoProduto, NomeDoProduto, PrecoUnitario FROM Produtos;
SELECT CodigoDaTransportadora, NomeDaEmpresa, Telefone FROM Transportadoras;
SELECT NomeDaEmpresa AS NomeDoCliente, Endereco, 'Cliente Preferencial' AS StatusCliente FROM Clientes;
SELECT CodigoDoProduto, 'Produto existente' AS SituacaoProduto, NomeDoProduto FROM Produtos;
SELECT Endereco, TelefoneResidencial, 'Pertence ao quadro' AS Vinculo, Ramal, 'Ativo' AS StatusFuncionario FROM Funcionarios;
SELECT NomeDaCategoria, Descricao, 'Definição' AS ColunaExtra FROM Categorias;
SELECT TOP(5) * FROM Pedidos;
SELECT TOP(15) * FROM Funcionarios;
SELECT TOP(3) NomeDaEmpresa FROM Fornecedores;
SELECT TOP(20) * FROM Produtos;
SELECT TOP(2) * FROM Categorias;
SELECT  Nome AS Funcionário, Cargo AS Função, Tratamento AS Título FROM Funcionarios;
SELECT  NomeDaEmpresa AS Empresa, NomeDoContato AS Contato, CargoDoContato AS Cargo FROM Fornecedores;
SELECT  Nome, TelefoneResidencial AS Fone, Observacoes AS Obs FROM Funcionarios;
SELECT NomeDaCategoria AS 'Categoria', Descricao 'Observação', 'Aprovado' AS Situacao FROM Categorias;
SELECT  CodigoDoProduto, NomeDoProduto, PrecoUnitario, PrecoUnitario * 1.07 AS PrecoComAcrescimo7 FROM Produtos;
SELECT  Nome, Sobrenome FROM Funcionarios ORDER BY Nome DESC;
SELECT  CodigoDoProduto, NomeDoProduto, PrecoUnitario FROM Produtos ORDER BY NomeDoProduto ASC;
SELECT CodigoDoProduto AS [Cód.], NomeDoProduto AS [Produto], PrecoUnitario AS [P. Unitário] FROM Produtos ORDER BY CodigoDoProduto DESC;
SELECT Pais, Regiao, CodigoDoFornecedor, NomeDaEmpresa, NomeDoContato FROM Fornecedores ORDER BY Pais ASC, Regiao DESC, NomeDaEmpresa ASC;
SELECT CodigoDoFuncionario, Sobrenome, Nome FROM Funcionarios ORDER BY Pais ASC;